### ISSUE TITLE
go ccpsdk CreateFile方法和文档中不一样

### ISSUE THREAD

**Issue by richarduncle** [aliyun/aliyun-ccp#261]
文档是这么写的：
	response, err := ccpClient.CreateFile(createFileRequest, runtime)
但是sdk中方法是：
func (client *Client) CreateFile(request *CCPCreateFileRequestModel, runtime *RuntimeOptions) (_result *CreateFileModel, _err error)

有点疑惑了，是不是哪里没找到？

是不是后面增加一步SetBody 文档没改啊？

**Comment by wenzuochao** [comment]
您看的是哪的文档呢，github上的文档没问题啊，https://github.com/aliyun/aliyun-ccp/blob/master/docs/usage-go.md#%E5%88%9B%E5%BB%BA-file-1，  https://github.com/aliyun/aliyun-ccp/blob/master/docs/usage-go.md#ccppath-%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6

**Comment by wenzuochao** [comment]
我这边先把issue关了，如果您还有其他问题的话，可以重新开一个issue
