### ISSUE TITLE
go get github.com/alibabacloud-go/ccppath-sdk/ccppath-sdk: no matching versions for query "upgrade"

### ISSUE THREAD

**Issue by haima95** [aliyun/aliyun-ccp#290]
go get  github.com/alibabacloud-go/ccppath-sdk/ccppath-sdk
go: finding github.com/alibabacloud-go/ccppath-sdk/ccppath-sdk latest
go get github.com/alibabacloud-go/ccppath-sdk/ccppath-sdk: no matching versions for query "upgrade"

下载异常

**Comment by wenzuochao** [comment]
使用 go get github.com/alibabacloud-go/ccppath-sdk

**Comment by wenzuochao** [comment]
如果没有其他问题的话，我将在3天之内关闭 issue，如果您还有其他问题，可以重新开一个 issue
